#!/usr/bin/env python3
"""
Research-to-product feedback harness for Oroma.

This is deliberately lightweight: it scans known Oroma control files and code
surfaces, then emits five markdown reports with developer-actionable findings.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
from dataclasses import dataclass
from pathlib import Path


REPORT_NAMES = [
    "product_recommendation.md",
    "engineering_risks.md",
    "ui_benchmark_findings.md",
    "backend_truth_findings.md",
    "test_gap_report.md",
]

SKIP_DIRS = {
    ".git",
    ".next",
    ".vercel",
    "node_modules",
    "__pycache__",
    ".archive",
    "graphify-out",
}


@dataclass
class Finding:
    claim: str
    evidence: str
    affected: str
    severity: str
    proposed_fix: str
    acceptance_test: str


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except FileNotFoundError:
        return ""


def exists(path: Path) -> str:
    return "present" if path.exists() else "missing"


def count_files(root: Path, patterns: list[str]) -> int:
    if not root.exists():
        return 0
    total = 0
    suffixes = [pattern.removeprefix("*") for pattern in patterns if pattern.startswith("*.")]
    exact = [pattern for pattern in patterns if not pattern.startswith("*.")]
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [name for name in dirnames if name not in SKIP_DIRS]
        for filename in filenames:
            if filename in exact or any(filename.endswith(suffix) for suffix in suffixes):
                total += 1
    return total


def md_table(findings: list[Finding]) -> str:
    rows = [
        "| Claim | Evidence | Affected files/routes | Severity | Proposed fix | Acceptance test |",
        "|---|---|---|---|---|---|",
    ]
    for item in findings:
        rows.append(
            "| "
            + " | ".join(
                cell.replace("\n", " ").replace("|", "\\|")
                for cell in [
                    item.claim,
                    item.evidence,
                    item.affected,
                    item.severity,
                    item.proposed_fix,
                    item.acceptance_test,
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def write_report(path: Path, title: str, findings: list[Finding], source_root: Path) -> None:
    today = dt.date.today().isoformat()
    body = [
        f"# {title}",
        "",
        f"Generated: {today}",
        f"Source repo: `{source_root}`",
        "",
        "## Findings",
        "",
        md_table(findings),
        "",
        "## Method Note",
        "",
        "This report is generated by `spine/research_feedback.py`. It is a first-pass research harness, not a final engineering verdict.",
        "",
    ]
    path.write_text("\n".join(body), encoding="utf-8")


def build_findings(oroma: Path) -> dict[str, list[Finding]]:
    ui_audit = read_text(oroma / "UI_AUDIT.md")
    yellowcard = read_text(oroma / "YELLOWCARD_REFERENCE_AUDIT.md")
    backend = read_text(oroma / "OROMA_BACKEND_ASSESSMENT.md")
    research_advisory = read_text(oroma / "RESEARCH_ADVISORY.md")
    agents = read_text(oroma / "AGENTS.md")

    app_pages = count_files(oroma / "frontend" / "app", ["page.tsx", "layout.tsx"])
    service_tests = count_files(oroma, ["*.test.ts", "*.spec.ts"])
    route_files = count_files(oroma / "apps" / "agents-api" / "src" / "routes", ["*.ts"])
    schema_files = count_files(oroma / "packages" / "db" / "src" / "schema", ["*.ts"])

    product = [
        Finding(
            "Oroma needs a source-backed product feedback loop, not one-off audits.",
            f"Control docs: UI_AUDIT={exists(oroma / 'UI_AUDIT.md')}, YELLOWCARD_REFERENCE_AUDIT={exists(oroma / 'YELLOWCARD_REFERENCE_AUDIT.md')}, RESEARCH_ADVISORY={exists(oroma / 'RESEARCH_ADVISORY.md')}.",
            "Repository-level product process",
            "HIGH",
            "Run this harness after major product changes and convert findings into implementation tickets.",
            "A generated report maps each recommendation to evidence, affected surface, fix, and acceptance test.",
        ),
        Finding(
            "Dashboard should answer institutional next-action questions before doctrine.",
            "UI audit flags dashboard realism gaps around money state, approvals, receipts, records, proof, and next action."
            if "Dashboard Realism Gaps" in ui_audit
            else "UI audit not found or missing dashboard realism section.",
            "frontend/app, frontend/components",
            "HIGH",
            "Prioritize dashboard modules for money state, pending approvals, receipt/proof state, dispute state, and next action.",
            "At 1440px and 390px, first screen answers: what changed, what is blocked, and what action matters now.",
        ),
    ]

    engineering = [
        Finding(
            "Backend truth is stronger than before but still not institution-grade.",
            "Backend assessment reports institutional-readiness score 1/5 and fakeability risk critical."
            if "institutional-readiness score" in backend
            else "Backend assessment not found or missing institutional-readiness verdict.",
            "apps/agents-api, packages/services, packages/db, contracts",
            "CRITICAL",
            "Treat identity binding, dispute authority, credential evidence, and ICEGOV lineage as blockers before pilot claims.",
            "Negative tests reject spoofed actor refs, fake wallet ownership, unsupported dispute closure, and unsupported credential issuance.",
        ),
        Finding(
            "Research indicators need enforced lineage, not UI labels.",
            "Research advisory lists DRL-01, CPS-01, TTI-01, and FID-01 implementation gaps."
            if "DRL-01" in research_advisory
            else "Research advisory not found or missing indicator gap list.",
            "contracts, services, frontend onboarding, records",
            "HIGH",
            "Map every research indicator to a schema field, service invariant, event, and frontend capture point.",
            "Extractor can compute each indicator from stored events without reading prose or mock data.",
        ),
    ]

    ui = [
        Finding(
            "Yellow Card should remain a benchmark for trust pacing, not a visual template.",
            "Reference audit emphasizes product claim, restrained CTA, trust narrative, and concrete product-world visual."
            if "What Makes It Feel Premium" in yellowcard
            else "Yellow Card reference audit not found.",
            "homepage, explore, workspace hub, dashboard",
            "MEDIUM",
            "Use Oroma-specific product visuals: contributions, approvals, disbursements, receipts, records, proof.",
            "Screenshots show product evidence above the fold without copying Yellow Card copy, layout, or assets.",
        ),
        Finding(
            "UI coverage must include mobile and desktop screenshot gates.",
            f"Frontend app has approximately {app_pages} page/layout files; generated QA screenshots exist but need report linkage.",
            "frontend/e2e, frontend/.qa-* artifacts",
            "MEDIUM",
            "Standardize screenshot QA report generation for 1440, 1024, 768, and 390 widths.",
            "Each important route has current screenshots and a written pass/fail note tied to product requirements.",
        ),
    ]

    backend_truth = [
        Finding(
            "Routes and schemas need claim-level traceability.",
            f"Observed route files: {route_files}; schema files: {schema_files}.",
            "apps/agents-api/src/routes, packages/db/src/schema",
            "HIGH",
            "For each public claim, record the route, service, schema, and test that enforce it.",
            "A claim map exists where every non-trivial product/research claim resolves to code and tests.",
        ),
        Finding(
            "Oroma constitution already defines the UX/truth bar; harness should enforce it.",
            "AGENTS.md states confusing real-person flows are not done and requires chain-state/economic legibility."
            if "If a page is technically correct but still confusing" in agents
            else "AGENTS.md not found or missing constitution text.",
            "frontend, services, docs",
            "MEDIUM",
            "Make this harness check for missing continuity, wallet readiness, money state, and proof language on key surfaces.",
            "Generated reports flag any key route that cannot answer user state, next action, chain authority, and proof state.",
        ),
    ]

    tests = [
        Finding(
            "Test reports should be generated from research gaps.",
            f"Approximate TS test/spec files found: {service_tests}.",
            "frontend/e2e, packages/services/src/__tests__, apps/agents-api/src/__tests__",
            "MEDIUM",
            "Convert every CRITICAL/HIGH research finding into at least one negative or acceptance test.",
            "Each generated report includes a test gap and a proposed test name or scenario.",
        ),
        Finding(
            "PAGC experiments must not run without documented source state.",
            "PAGC reset requires source archive, extraction method, and falsification condition before experiments.",
            "research/pagc, experiments/01_bpe_igbo_k27",
            "HIGH",
            "Block future PAGC experiment reports unless they cite primary source manifest and corpus manifest.",
            "Experiment report includes source files, corpus manifest, baseline, metric, and falsification rule.",
        ),
    ]

    return {
        "product_recommendation.md": product,
        "engineering_risks.md": engineering,
        "ui_benchmark_findings.md": ui,
        "backend_truth_findings.md": backend_truth,
        "test_gap_report.md": tests,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Oroma research feedback reports.")
    parser.add_argument("--oroma", default="../oroma", help="Path to the Oroma repo.")
    parser.add_argument("--out", default=None, help="Output directory. Defaults to research/product_feedback/YYYY-MM-DD.")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    oroma = (repo_root / args.oroma).resolve()
    out = Path(args.out) if args.out else repo_root / "research" / "product_feedback" / dt.date.today().isoformat()
    out.mkdir(parents=True, exist_ok=True)

    findings = build_findings(oroma)
    titles = {
        "product_recommendation.md": "Product Recommendations",
        "engineering_risks.md": "Engineering Risks",
        "ui_benchmark_findings.md": "UI Benchmark Findings",
        "backend_truth_findings.md": "Backend Truth Findings",
        "test_gap_report.md": "Test Gap Report",
    }
    for report_name in REPORT_NAMES:
        write_report(out / report_name, titles[report_name], findings[report_name], oroma)

    index = [
        "# Research Feedback Run",
        "",
        f"Generated: {dt.date.today().isoformat()}",
        f"Source repo: `{oroma}`",
        "",
        "## Reports",
        "",
    ]
    for report_name in REPORT_NAMES:
        index.append(f"- [{report_name}]({report_name})")
    index.append("")
    (out / "INDEX.md").write_text("\n".join(index), encoding="utf-8")
    print(f"Wrote research feedback reports to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
